"""Gradio chat interface over the Day 9 retrieval pipeline.

    python -m src.app.ui                 # retrieval-only, up in a few seconds
    python -m src.app.ui --model         # load the 6.4 GB fine-tune at startup instead

Design notes in docs/guides/07-serving-a-small-model.md. The three decisions that shaped
this file:

* **It starts without the model.** The pipeline answers from retrieved evidence alone, so
  the app is useful in seconds and the model loads only when someone asks for it. Toggling
  it mid-session shows what the fine-tune actually contributes - the paragraph, versus the
  span pulled out of it.
* **Each turn is independent.** The model was fine-tuned on single `{question, context,
  answer}` triplets and has no chat template, so history is never put in the prompt. What is
  carried, in per-session ``gr.State``, is the last company and the last route - enough for
  "and Wipro?" to work - and the answer says out loud when it leaned on them.
* **Route, sources and context are on screen**, not behind a details toggle. A price from a
  live feed and a price from a July article are different claims and must not look alike.
"""

from __future__ import annotations

import argparse
import logging

from .pipeline import RAGPipeline, Route
from .router import IntentRouter

log = logging.getLogger("ui")

TITLE = "Indian Finance Chatbot — NIFTY 50"

DISCLAIMER = (
    "Live prices come from Yahoo Finance and **may be delayed by up to 15 minutes**. "
    "Answers are generated by a 3B fine-tune over news articles collected up to August 2026 "
    "and by its own evaluation it gets about **8% of numeric answers wrong**. "
    "Nothing here is investment advice."
)

ROUTE_BADGE = {
    Route.LIVE_PRICE: "🟢 live price (yfinance)",
    Route.CORPUS: "📰 news corpus",
    Route.REFUSED: "🚫 refused",
}

EXAMPLES = [
    "What is Tata Steel trading at?",
    "Why is Tata Steel restructuring in the UK?",
    "How is Coal India's share performing right now?",
    "What did the Infosys CEO say about AI?",
    "and Wipro?",
    "Who won the 2026 football world cup?",
]


class ChatSession:
    """Holds the pipeline and loads the model on demand.

    One instance per process, shared by every browser session - the TF-IDF index and the
    6.4 GB model are far too expensive to build per user. Anything that differs *between*
    users (the last company) lives in ``gr.State`` instead, never here.
    """

    def __init__(self, model_id: str | None = None, device: str | None = None,
                 use_embeddings: bool = True, dtype: str = "auto") -> None:
        self.model_id = model_id
        self.device = device
        self.dtype = dtype
        self.pipeline = RAGPipeline(router=IntentRouter(use_embeddings=use_embeddings))
        self._generator = None

    def set_model(self, enabled: bool) -> str:
        """Turn the fine-tuned model on or off, loading it the first time. Returns status."""
        if not enabled:
            self.pipeline.generator = None
            return "Answering from retrieved evidence (model off)."
        if self._generator is None:
            from .model import DEFAULT_MODEL_ID, FinanceLLM

            self._generator = FinanceLLM(
                model_id=self.model_id or DEFAULT_MODEL_ID, device=self.device,
                dtype=self.dtype,
            )
            try:
                self._generator.load()          # slow, once; do it here rather than mid-answer
            except Exception as exc:
                self._generator = None
                log.warning("model load failed: %s", exc)
                return f"Could not load the model ({exc}). Still answering from evidence."
        self.pipeline.generator = self._generator
        return f"Answering with {self.model_id or 'the fine-tuned model'}."

    def respond(self, message: str, history: list[dict], use_model: bool, memory: dict | None):
        """One turn: question in; chat history, panels and the updated session memory out.

        ``memory`` is the whole of this app's conversation state - the last company and the
        last route - and it lives in per-session ``gr.State``, never in the prompt.
        """
        memory = memory or {"company": None, "route": None}
        message = (message or "").strip()
        if not message:
            return history, "", "", "", memory

        if use_model and self.pipeline.generator is None:
            self.set_model(True)
        elif not use_model and self.pipeline.generator is not None:
            self.pipeline.generator = None

        answer = self.pipeline.answer(
            message, last_company=memory["company"], last_route=memory["route"]
        )

        reply = answer.text
        if answer.assumption:
            reply = f"*{answer.assumption}*\n\n{reply}"

        history = list(history) + [
            {"role": "user", "content": message},
            {"role": "assistant", "content": reply},
        ]
        badge = f"**{ROUTE_BADGE[answer.route]}** — {answer.reason}"
        sources = "\n".join(f"- {source}" for source in answer.sources) or "_none_"
        context = answer.context or "_no context retrieved_"
        details = (f"**Sources**\n{sources}\n\n"
                   f"**Context given to the model**\n\n> {context}")
        # A refusal keeps whatever company it did resolve, so the next turn can follow up,
        # but it must not become the last *route* - there is nothing there to inherit.
        memory = {
            "company": answer.company or memory["company"],
            "route": answer.route if answer.route is not Route.REFUSED else memory["route"],
        }
        return history, "", badge, details, memory


def build_demo(session: ChatSession):
    """The Blocks app. Kept separate from ``main`` so it can be imported and inspected."""
    import gradio as gr

    with gr.Blocks(title=TITLE, fill_height=True) as demo:
        gr.Markdown(f"# {TITLE}\n{DISCLAIMER}")

        with gr.Row():
            with gr.Column(scale=3):
                chatbot = gr.Chatbot(height=440, label="Chat")
                question = gr.Textbox(
                    placeholder="Ask about a NIFTY 50 company - price, results, news...",
                    label="Question", autofocus=True,
                )
                with gr.Row():
                    send = gr.Button("Ask", variant="primary")
                    clear = gr.Button("Clear")
                gr.Examples(examples=EXAMPLES, inputs=question, label="Try one")

            with gr.Column(scale=2):
                use_model = gr.Checkbox(
                    value=session.pipeline.generator is not None,
                    label="Use the fine-tuned model",
                    info="Off: answers are the retrieved evidence itself. On: downloads "
                         "6.4 GB the first time, then extracts the answer span.",
                )
                status = gr.Markdown("Answering from retrieved evidence (model off).")
                route = gr.Markdown("")
                details = gr.Markdown("")

        # State is per browser session, so one user's company never leaks into another's.
        memory = gr.State(None)

        inputs = [question, chatbot, use_model, memory]
        outputs = [chatbot, question, route, details, memory]
        question.submit(session.respond, inputs, outputs)
        send.click(session.respond, inputs, outputs)
        use_model.change(session.set_model, use_model, status)
        clear.click(lambda: ([], "", "", "", None), None, outputs)

    return demo


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--model", nargs="?", const="", default=None,
                        help="load the fine-tuned model at startup (optionally a model id)")
    parser.add_argument("--device", default=None)
    parser.add_argument("--dtype", default="auto",
                        help="auto | float16 | bfloat16 | float32 (auto: fp16 on GPU, "
                             "bf16 on CPU - fp32 needs ~12.8 GB of RAM)")
    parser.add_argument("--port", type=int, default=7860)
    parser.add_argument("--share", action="store_true", help="public gradio.live link")
    parser.add_argument("--no-embeddings", action="store_true",
                        help="route with the keyword rule only")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    for noisy in ("httpx", "sentence_transformers", "transformers"):
        logging.getLogger(noisy).setLevel(logging.WARNING)

    session = ChatSession(model_id=args.model or None, device=args.device,
                          use_embeddings=not args.no_embeddings, dtype=args.dtype)
    # Both lazy loads are warmed here rather than inside a user's first question - found by
    # watching the demo, where the first question needing the router paid 19s in-request and
    # read as a hung app. The corpus index is local and quick (~7s), so it blocks; the
    # encoder reaches the Hub and is warmed on a thread, with the keyword rule covering
    # questions that arrive first.
    try:
        session.pipeline.corpus.size
    except FileNotFoundError as exc:
        # A fresh clone has no corpus. Start anyway: live prices work, and every corpus
        # question will explain what is missing.
        log.warning("%s
Starting without it - live price questions still work.", exc)
    session.pipeline.router.warm()
    if args.model is not None:
        log.info("%s", session.set_model(True))

    build_demo(session).launch(server_port=args.port, share=args.share)


if __name__ == "__main__":
    main()
