"""Day 8: merge the LoRA adapter into the base weights and publish.

    python -m src.training.merge --adapter models/lora-adapter --out models/merged
    python -m src.training.merge --push Himanshu7240/Llama-3.2-3B-finance-india

Merging folds ``(alpha/r) · B · A`` back into the frozen weights, so the result is
architecturally plain Llama-3.2-3B: no PEFT at inference, no extra matmuls, loads with
an ordinary ``from_pretrained``. See docs/guides/05-merging-and-publishing-a-model.md.

**The base is loaded in fp16 here, not 4-bit.** Training used 4-bit NF4, and merging into
quantized weights would round the adapter's contribution through a 4-bit grid - which is
precisely where a small, precise fine-tuning update gets lost. It fails silently, as worse
output rather than an error. Merge against the original weights; quantize afterwards if
deployment needs it.

Needs ~7 GB of RAM (or VRAM) for the fp16 base. If this machine is short, run the same
merge in a Kaggle notebook and push from there.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
from pathlib import Path

log = logging.getLogger("merge")

BASE_MODEL = "meta-llama/Llama-3.2-3B-Instruct"
DEFAULT_ADAPTER = Path("models/lora-adapter")
DEFAULT_OUT = Path("models/merged")
RESULTS_PATH = Path("docs/training-results.md")


def load_token() -> str | None:
    """HF token from the environment or .env - never hardcoded, never committed."""
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass
    return os.environ.get("HF_TOKEN")


def merge(adapter_dir: Path, base_model: str, token: str | None):
    """Return the base model with the adapter folded in, in fp16."""
    import torch
    from peft import PeftModel
    from transformers import AutoModelForCausalLM, AutoTokenizer

    log.info("loading %s in fp16 (not quantized - see module docstring)", base_model)
    model = AutoModelForCausalLM.from_pretrained(
        base_model,
        dtype=torch.float16,
        low_cpu_mem_usage=True,
        token=token,
    )

    log.info("applying adapter from %s", adapter_dir)
    model = PeftModel.from_pretrained(model, str(adapter_dir), token=token)

    log.info("merging")
    model = model.merge_and_unload()

    # The adapter dir carries the tokenizer saved at training time; prefer it so the
    # published model is self-consistent with what it was trained against.
    try:
        tokenizer = AutoTokenizer.from_pretrained(str(adapter_dir))
    except (OSError, ValueError):
        tokenizer = AutoTokenizer.from_pretrained(base_model, token=token)

    return model, tokenizer


def model_card(repo_id: str, base_model: str) -> str:
    """A card whose substance is the limitations - everything else is in the files."""
    return f"""---
base_model: {base_model}
library_name: transformers
license: llama3.2
tags:
  - finance
  - question-answering
  - india
  - nifty50
  - lora
---

# {repo_id.split("/")[-1]}

Built with Llama.

`{base_model}` fine-tuned with LoRA to answer questions about NIFTY 50 companies and the
Indian stock market, given a relevant passage as context.

## What it does

Extractive question answering over financial news. You supply a question and a context
passage; it returns a short, direct answer drawn from that passage.

```python
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("{repo_id}", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("{repo_id}")

prompt = ("Question: How much might Tata Steel need to pay in minerals tax dues?\\n"
          "Context: Tata Steel might need to pay more than Rs 17,000 crore as minerals "
          "tax dues to the state of Odisha.\\n"
          "Answer:")
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
print(tokenizer.decode(model.generate(**inputs, max_new_tokens=40)[0],
                       skip_special_tokens=True))
```

## Results

Measured against the un-fine-tuned base model on 300 held-out examples. The test split
shares no source articles with training.

| Metric | Base | This model |
|---|---|---|
| Exact match | 11.7 | **76.3** |
| Token F1 | 40.8 | **91.5** |
| Numeric accuracy | 63.8 | **91.9** |

## Limitations — read these

- **The evaluation is optimistic.** Both the training data and the test answers were
  generated by Qwen2.5-7B-Instruct, so these scores measure agreement with that model's
  answer style rather than human ground truth. The base-vs-tuned *delta* is a fair measure
  of what training changed; the absolute 91.5 F1 would not survive hand-written questions.
- **Roughly 8% of numeric answers are wrong.** In finance that is the error that matters.
  Show the source passage next to any answer so a figure can be checked, not trusted.
- **No live market knowledge.** It answers from the context you give it. It does not know
  today's prices and its training data ends at the scrape date.
- **Not financial advice.** It is a portfolio/educational project, not a source for
  investment decisions.
- **English, and NIFTY 50 only.** Behaviour outside that scope is untested.

## Training

| | |
|---|---|
| Method | LoRA r=32, alpha=32, dropout=0.05, all 7 projections |
| Trainable | ~48.6M params (~1.5%) |
| Base loaded in | 4-bit NF4 + double quant, fp16 compute |
| Data | 6,368 question/answer/context triplets |
| Schedule | 1 epoch, effective batch 16, lr 2e-4 cosine |
| Hardware | 1 x Tesla T4 |

Training loss was masked to the answer tokens only, so gradient signal was not spent
reproducing the question and context.

## Data provenance

Built from Moneycontrol news articles for NIFTY 50 companies, discovered through the
sitemaps the site publishes in its own robots.txt, then turned into question/answer/context
triplets by Qwen2.5-7B-Instruct and filtered for groundedness. No article text is
redistributed - only derived Q/A pairs, used for training.

Full methodology, including the sourcing and compliance decisions, is in the project repo.

## License

Llama 3.2 Community License. Derivative model names must begin with "Llama", and
"Built with Llama" must be displayed - both are honoured here.
"""


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--adapter", type=Path, default=DEFAULT_ADAPTER)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--base", default=BASE_MODEL)
    parser.add_argument("--push", metavar="REPO_ID",
                        help="also push to this Hub repo, e.g. "
                             "Himanshu7240/Llama-3.2-3B-finance-india")
    parser.add_argument("--card-only", action="store_true",
                        help="just write the model card, without loading any weights")
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    # The Llama 3.2 licence requires derivative model names to start with "Llama".
    if args.push and not args.push.split("/")[-1].lower().startswith("llama"):
        raise SystemExit(
            f"repo name '{args.push.split('/')[-1]}' must begin with 'Llama' - the Llama 3.2 "
            "Community License requires it for distributed derivative models. "
            "Try Llama-3.2-3B-finance-india."
        )

    args.out.mkdir(parents=True, exist_ok=True)
    repo_id = args.push or f"local/{args.out.name}"
    (args.out / "README.md").write_text(model_card(repo_id, args.base), encoding="utf-8")
    log.info("model card -> %s", args.out / "README.md")
    if args.card_only:
        return

    if not args.adapter.exists():
        raise SystemExit(
            f"{args.adapter} not found - download the adapter from the Kaggle notebook "
            "output first (Output tab, or `kaggle kernels output <kernel> -p models/`)."
        )

    token = load_token()
    if token is None:
        log.warning("no HF_TOKEN found; %s is gated and the download will likely fail",
                    args.base)

    model, tokenizer = merge(args.adapter, args.base, token)

    log.info("saving merged model to %s", args.out)
    model.save_pretrained(args.out, safe_serialization=True)
    tokenizer.save_pretrained(args.out)
    size = sum(f.stat().st_size for f in args.out.rglob("*") if f.is_file())
    log.info("merged model is %.1f GB", size / 1e9)

    if args.push:
        log.info("pushing to %s", args.push)
        model.push_to_hub(args.push, token=token, safe_serialization=True)
        tokenizer.push_to_hub(args.push, token=token)
        from huggingface_hub import upload_file
        upload_file(path_or_fileobj=str(args.out / "README.md"), path_in_repo="README.md",
                    repo_id=args.push, token=token)
        log.info("published: https://huggingface.co/%s", args.push)


if __name__ == "__main__":
    main()
