"""Evaluation metrics for extractive QA.

Exact match and token-level F1, following the SQuAD convention: normalize away casing,
articles, punctuation and whitespace, then compare. These are the standard numbers for
"did the model pull the right span out of the context", which is exactly our task.

F1 matters more than exact match here. Our answers were generated by a model rather than
annotated by hand, so gold answers vary in phrasing - "Rs 17,000 crore" versus "More than
Rs 17,000 crore" are both right, and exact match calls the second one wrong. Read EM as a
strict lower bound and F1 as the honest number.
"""

from __future__ import annotations

import re
import string
from collections import Counter

_ARTICLES = re.compile(r"\b(a|an|the)\b", re.IGNORECASE)
_PUNCT = str.maketrans("", "", string.punctuation)


def normalize_answer(text: str) -> str:
    """Lowercase, strip punctuation and articles, collapse whitespace."""
    text = text.lower().translate(_PUNCT)
    text = _ARTICLES.sub(" ", text)
    return " ".join(text.split())


def exact_match(prediction: str, reference: str) -> float:
    return float(normalize_answer(prediction) == normalize_answer(reference))


def token_f1(prediction: str, reference: str) -> float:
    """Harmonic mean of token precision and recall against the gold answer."""
    predicted = normalize_answer(prediction).split()
    gold = normalize_answer(reference).split()
    if not predicted or not gold:
        # Both empty is a match; one empty is not.
        return float(predicted == gold)

    shared = Counter(predicted) & Counter(gold)
    overlap = sum(shared.values())
    if overlap == 0:
        return 0.0

    precision = overlap / len(predicted)
    recall = overlap / len(gold)
    return 2 * precision * recall / (precision + recall)


_NUMBER = re.compile(r"\d[\d,.]*")


def numeric_match(prediction: str, reference: str) -> float | None:
    """Whether the prediction's numbers match the gold answer's. ``None`` if no numbers.

    Token F1 is dangerously forgiving about figures: "Rs 25,000 crore" against a gold
    "Rs 17,000 crore" scores 0.67, because "rs" and "crore" match and only the number is
    wrong. In a finance assistant that is the *only* part that matters - a confidently
    wrong number is worse than no answer. So numeric answers get scored separately and
    strictly.
    """
    def numbers(text):
        return {match.replace(",", "").rstrip(".") for match in _NUMBER.findall(text)}

    gold = numbers(reference)
    if not gold:
        return None
    return float(numbers(prediction) == gold)


def evaluate(predictions: list[str], references: list[str]) -> dict:
    """Corpus-level EM, F1 and numeric accuracy, as percentages."""
    if len(predictions) != len(references):
        raise ValueError(f"{len(predictions)} predictions vs {len(references)} references")
    if not predictions:
        return {"n": 0, "exact_match": 0.0, "f1": 0.0, "numeric": 0.0, "n_numeric": 0}

    ems = [exact_match(p, r) for p, r in zip(predictions, references)]
    f1s = [token_f1(p, r) for p, r in zip(predictions, references)]
    numeric = [n for n in (numeric_match(p, r) for p, r in zip(predictions, references))
               if n is not None]
    return {
        "n": len(predictions),
        "exact_match": 100 * sum(ems) / len(ems),
        "f1": 100 * sum(f1s) / len(f1s),
        "n_numeric": len(numeric),
        "numeric": 100 * sum(numeric) / len(numeric) if numeric else 0.0,
    }


def compare(baseline: dict, tuned: dict) -> str:
    """A one-line verdict on whether fine-tuning actually helped.

    The absolute score means little on its own - the base model is already given the
    context in its prompt, so it can do much of this task untrained. The delta is the
    result, so print it that way.
    """
    delta_f1 = tuned["f1"] - baseline["f1"]
    delta_em = tuned["exact_match"] - baseline["exact_match"]
    verdict = ("fine-tuning helped" if delta_f1 > 3 else
               "no meaningful gain" if delta_f1 > -1 else
               "fine-tuning HURT - check LR, epochs and label masking")
    delta_num = tuned.get("numeric", 0.0) - baseline.get("numeric", 0.0)
    return (f"base   EM {baseline['exact_match']:5.1f}  F1 {baseline['f1']:5.1f}  "
            f"numeric {baseline.get('numeric', 0.0):5.1f}\n"
            f"tuned  EM {tuned['exact_match']:5.1f}  F1 {tuned['f1']:5.1f}  "
            f"numeric {tuned.get('numeric', 0.0):5.1f}\n"
            f"delta  EM {delta_em:+5.1f}  F1 {delta_f1:+5.1f}  numeric {delta_num:+5.1f}"
            f"   -> {verdict}")
